import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { CartProvider } from '@/components/Client/CartContext'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Stripe Integration With NextJs',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider><div>{children}</div></CartProvider>
      </body>
    </html>
  )
}
